name: ElectriGo C.I.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-all: 
                          
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1.2.*
      with:
        dotnet-version: 6.0.x
    - name: Build .NET
      run: echo 'Doing c# build' && dotnet build --no-restore
